### PR TITLE
Remove MCT from code base

### LINKED ISSUE #33: Update path to cime tools in buildlib/buildnml
The path for cime tools was changed from cime/script/Tools to cime/CIME/Tools in cime6.0.17. This path is also set in buildlib and buildnml and should be updated. cime magic allows this to work as it is, but to prevent the confusion of setting to a directory that doesn't exist, to allow these scripts to be run outside a case, and to prevent future problems this should be updated.

### LINKED ISSUE #41: Move Cheyenne test list to Derecho
Move the Cheyenne test list to Derecho

### LINKED ISSUE #44: Lower testing of RTM in CESM3
The use of RTM is now only for Paleo work in CESM3. As such we should lower the testing for it, and only test what's needed for Paleo work in CESM3. In CESM4 we hope to move to mizuRoute and hence remove RTM in CESM4.

This relates to #42

### LINKED ISSUE #45: Failing tests for RTM test list with ctsm5.1.dev161
When existing RTM tag rtm1_0_78 is used with ctsm5.1.dev161 theese two izumi tests fail, because of a CTSM issue:

ERS_Ld5.f10_f10_mg37.I2000Clm50BgcCropRtm.izumi_nag.rtm-default		
SMS_Ld5.f10_f10_mg37.I2000Clm50BgcCropRtm.izumi_nag.rtm-rtmColdStart

We just need to have them use DEBUG mode rather than production.

### PR DESCRIPTION
**Pull request by mvertens**
This PR just removes MCT code that is no longer used since it is only in the mct cap.

Resolves #45
Resolves #44
Resolves #41
Resolves #33

### CODE REVIEW

**Review by jedwards4b — APPROVED** [review]

**Review by ekluzek — APPROVED** [review]
This removes the MCT code. It looks like there was no use of MCT inside of the NUOPC cap.

Using "git grep" I see a few other instances of MCT to remove, which doesn't really matter. But, I'll do that. I'm also making a few other changes to tests and such.

@mvertens thanks for putting this together. I had assumed the same changes as MOSART needed to be done, but this shows it's really straight forward. However, it's still helpful to have someone verify this for us.

**Comment by ekluzek** [comment]
With this update about flooding we realized we need to add back in the flooding tests that I removed.

https://github.com/ESCOMP/RTM/issues/44#issuecomment-1897892708

So I'll do that and run those tests for the baseline. @slevis-lmwg and I are going to meet again on Friday to do RTM/MOSART tags.

**Comment by ekluzek** [comment]
I ran the new flooding tests, and they are fine. So testing looks good and this tag is ready to be made.

**Comment by ekluzek** [comment]
When @slevis-lmwg and I merged to master, we realized there was a commit on master that wasn't associated with a tag and was not included in this branch. The process that we had caught this as a problem, so it's easy to rerun the testlist at this point.

This means the tests need to be rerun. So I'll do that and then we'll make the actual tag.

**Pull request merged**
