### PR TITLE
Change time to equal the middle of time_bounds

### PR DESCRIPTION
**Pull request by slevis-lmwg**
RTM equivalent to CTSM work done in https://github.com/ESCOMP/CTSM/pull/2838

Relates to issue https://github.com/ESCOMP/RTM/issues/32 but does not resolve the separation of instantaneous variables onto separate history files.

@slevis-lmwg will track here also the prerequisite work happening in #54/#55.

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
Pinging myself in case I can subsequently assign myself to the PR...
@slevis-lmwg

**Comment by slevis-lmwg** [comment]
on derecho:
IN PROG ./run_sys_tests -s rtm -c rtm1_0_81-ctsm5.2.009 -g rtm1_0_82-ctsm5.2.009

**Comment by slevis-lmwg** [comment]
@ekluzek this is ready for your approval before I can merge.

**Comment by slevis-lmwg** [comment]
Then this will be rtm1_0_82.

**Review by ekluzek — APPROVED** [review]
LGTM. This is just doing the same thing as is being put into CTSM.

**Pull request merged**
