### PR TITLE
Update testlist_rtm

### LINKED ISSUE #54: Change the compsets being tested in our RTM testlists
The main purpose keeping RTM is for the use of the NoAnthro tests for Clm60, and for continuing to test the Clm45 compsets where RTM was the standard ROF model being used. There's also a Clm50 compset with RTM for the FLOOD option in RTM. Since, FLOOD is currently only working in RTM, we should continue testing it. It's also good to have at least 1850 and 2000 and possibly HIST. Since, nothing changes for RTM for transient cases, it's probably sufficient to have 1850 tests.

### PR DESCRIPTION
**Pull request by slevis-lmwg**
As recommended by @ekluzek 

Resolves #54

### CODE REVIEW

**Comment by slevis-lmwg** [comment]
Generating baselines:
`./run_sys_tests -s rtm -c rtm1_0_80-ctsm5.2.029 -g rtm1_0_80-ctsm5.3.009`

**Comment by slevis-lmwg** [comment]
Comparing to baselines on derecho:
`./run_sys_tests -s rtm -g rtm1_0_81-ctsm5.2.009 -c rtm1_0_80-ctsm5.3.009`

**Comment by slevis-lmwg** [comment]
- [ ] When rtm test suite completes, make tag and merge

**Comment by slevis-lmwg** [comment]
@ekluzek most tests failed with the following errors:
```
ERROR: Invalid compset name, I1850Clm45Sp, all stub components generated
ERROR: Invalid compset name, I2000Clm60SpNoAnthro, all stub components generated
```
The first could be replaced with one of these:
```
I1850Clm45BgcCrop
I1850Clm45BgcCru
I1850Clm45Bgc
```
The second could be replaced with one of these (though I assume the Rs is no good for running rtm):
```
I2000Clm60Sp
I2000Clm60SpRs
```
I will try the 3rd from the first list and the 1st from the second list, and I will resubmit the test suite.

**Comment by slevis-lmwg** [comment]
Rethinking the above choices to:
I2000Clm45Sp
I1850Clm60SpNoAnthro

**Comment by slevis-lmwg** [comment]
New problem with the NoAnthro compset:
err=ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.

Removed NoAnthro and got next error:
ERROR: No variable RTM_FLOOD_MODE found in case

@ekluzek we probably need to discuss what we want here before I go down a rabbit hole to resolve this.

**Comment by slevis-lmwg** [comment]
From meeting with @ekluzek 
Change the NoAnthro tests to f09.

**Comment by slevis-lmwg** [comment]
New tests
IN PROGRESS ./run_sys_tests -s rtm -g rtm1_0_81-ctsm5.2.009 -c rtm1_0_80-ctsm5.3.009
in /glade/derecho/scratch/slevis/tests_1108-140627de

**Comment by slevis-lmwg** [comment]
@jedwards4b this PR changes tests in the rtm testlist. I ran the rtm test-suite and they work. Would you be willing to approve my PR?

**Review by jedwards4b — APPROVED** [review]
LGTM - thanks

**Pull request merged**
